[build]
  # Next.js static export outputs to the 'out' directory
  publish = "out" 
  # This sets the command to run the static export
  command = "npm run build"
  
# This section ensures that all requests go to the index.html file
# which is necessary for Single Page Applications (SPAs)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200